# Generated by Django 5.1.3 on 2024-11-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebApp.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoWebApp.vuelo')),
            ],
        ),
    ]
